# Generated by Django 4.1 on 2022-09-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.CharField(max_length=70, primary_key=True, serialize=False, unique=True),
        ),
    ]
